import pygame

RESTART_EVENT = pygame.USEREVENT + 1
PREVIOUS_EVENT = pygame.USEREVENT + 2
NEXT_EVENT = pygame.USEREVENT + 3
RANDOM_GAME_EVENT = pygame.USEREVENT + 4
SOLVE_BFS_EVENT = pygame.USEREVENT + 5
SOLVE_ASTARMAN_EVENT = pygame.USEREVENT + 6
SOLVE_DIJKSTRA_EVENT = pygame.USEREVENT + 7
MOVE_UP_EVENT = pygame.USEREVENT + 8
MOVE_DOWN_EVENT = pygame.USEREVENT + 9
MOVE_LEFT_EVENT = pygame.USEREVENT + 10
MOVE_RIGHT_EVENT = pygame.USEREVENT + 11